services:
  mongo:
    container_name: testing-mongo
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  mongotest:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test123
    ports:
      - 27017:27017
volumes:
  mongo-data:
